# -*- coding: utf-8 -*-
"""config.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vn59knhIZLXcCt9Hx-pbRdNhPgnpZlhq
"""

db_password = 'WildW0lf!'